// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUvFuHgA79YAGTEDT2HRiU9bEGVerRn2s',
    appId: '1:82788046448:android:58270e5c41675659ae86b5',
    messagingSenderId: '82788046448',
    projectId: 'mus-voc-extractor',
    storageBucket: 'mus-voc-extractor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO2JUXGe3ghT5aqp-2kSQWbbY1P73QEpM',
    appId: '1:82788046448:ios:cd9957a7b3687bfbae86b5',
    messagingSenderId: '82788046448',
    projectId: 'mus-voc-extractor',
    storageBucket: 'mus-voc-extractor.appspot.com',
    iosBundleId: 'com.northernerwolf.vocalExtractionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO2JUXGe3ghT5aqp-2kSQWbbY1P73QEpM',
    appId: '1:82788046448:ios:6b78575d25fd1044ae86b5',
    messagingSenderId: '82788046448',
    projectId: 'mus-voc-extractor',
    storageBucket: 'mus-voc-extractor.appspot.com',
    iosBundleId: 'com.example.vocalExtractionApp.RunnerTests',
  );
}
